### ISSUE TITLE
timeSum not adding time

### ISSUE THREAD

**Issue by GeorisVal** [l4ur4nn3/timerApplication#4]
Time is not added correctly to the timeSum ID (bottom time), thus not giving any result for the calculation for the finalSalary ID

Screenshot:
![image](https://i.imgur.com/NFU5udE.png)

**Comment by l4ur4nn3** [comment]
where did I go wrong I've lost a friend🎶

**Comment by l4ur4nn3** [comment]
It adds the time entered in the calendar only
